// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwT_DCSKfkPat8eslIQWWkvgyG2hBpvyM',
    appId: '1:67837084425:web:f846ec92d5dce9490bc9d8',
    messagingSenderId: '67837084425',
    projectId: 'notesappbyraj',
    authDomain: 'notesappbyraj.firebaseapp.com',
    storageBucket: 'notesappbyraj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiY467SfrgE1oQrfiixfMhlPBZwuHJihk',
    appId: '1:67837084425:android:07b7a717495ab6ec0bc9d8',
    messagingSenderId: '67837084425',
    projectId: 'notesappbyraj',
    storageBucket: 'notesappbyraj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAouyw430qfYbCG0nTxzyXeQmMZPgwSN-M',
    appId: '1:67837084425:ios:b6ca487adc7a41e50bc9d8',
    messagingSenderId: '67837084425',
    projectId: 'notesappbyraj',
    storageBucket: 'notesappbyraj.appspot.com',
    iosClientId: '67837084425-g9dvlsob6lojkpiponfq3up35n5vvb6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );
}
